# -*- coding: utf-8 -*-
"""utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DziQRQO9JP5b0tQePX0D0vgHEUlbdfPV
"""

#import librires

import torch
from torchvision import transforms
from torch.utils.data import DataLoader , Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix
)

from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

#from google.colab import userdata
#from google.colab.userdata import SecretNotFoundError

import os
import opendatasets as od
"""
Download Kaggle dataset securely in Colab environment.

This code:
- Loads Kaggle credentials from Colab secrets
- Sets environment variables for authentication
- Downloads dataset using opendatasets library
"""

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')



def download_dataset():
    os.environ['KAGGLE_USERNAME']= "basemmorad"
    os.environ['KAGGLE_KEY']= "7b2fbf771941745848a7e98bf707751d"


    od.download("https://www.kaggle.com/datasets/aryashah2k/breast-ultrasound-images-dataset")

"""
Dataset configuration and class mapping setup.

This section defines:
- DATA_PATH: Root directory of the dataset
- CLASSES: List of class names in the dataset
- CLASS_TO_IDX: Mapping from class names to numeric labels (used for training)
- IDX_TO_CLASS: Reverse mapping from numeric labels back to class names (used for interpretation and visualization)

These mappings ensure consistent labeling across data loading, training, and evaluation stages.
"""

DATA_PATH = r"C:\Users\basem\Desktop\Final project\breast-ultrasound-images-dataset\Dataset_BUSI_with_GT"
CLASSES = ["benign", "malignant"]
CLASS_TO_IDX = {"benign": 0, "malignant": 1}
IDX_TO_CLASS = {0: "benign", 1: "malignant"}

"""
Load image paths and labels from dataset folders.

Reads images from each class folder, skips mask files,
and maps class names to numeric labels.
Returns lists of image paths and labels.
"""
def load_data(data_path=DATA_PATH):
    images = []
    labels = []

    for cls in CLASSES:
        folder_path = os.path.join(data_path, cls)
        files = [f for f in os.listdir(folder_path) if 'mask' not in f]

        for img_name in files:
            img_path = os.path.join(folder_path, img_name)
            images.append(img_path)
            labels.append(CLASS_TO_IDX[cls])

    print(f"Total images: {len(images)}")
    return images, labels


"""
Split dataset into training, validation, and test sets.

This function:
- Splits the original dataset into train and temporary sets
- Then splits the temporary set into validation and test sets
- Uses stratification to maintain class distribution across all splits
- Ensures reproducibility using a fixed random state

Args:
    images (list): List of image paths
    labels (list): Corresponding class labels
    val_size (float): Fraction of data for validation set
    test_size (float): Fraction of data for test set
    random_state (int): Seed for reproducibility

Returns:
    tuple: train_images, val_images, test_images, train_labels, val_labels, test_labels
"""

def split_data(images,labels,val_size=0.2,test_size=0.2,random_state=42):

#plit data to train and temp

  train_images,temp_images,train_labels,temp_labels=train_test_split(
      images,
      labels,
      test_size=(val_size+test_size),
      stratify=labels,
      random_state=random_state

  )

# split temp to val and test
  val_images,test_images,val_labels,test_labels=train_test_split(

      temp_images,
      temp_labels,
      test_size=0.5,
      stratify=temp_labels,
      random_state=random_state
  )

  print(f"Train: {len(train_images)} | Val: {len(val_images)} | Test: {len(test_images)}")
  return train_images, val_images, test_images, train_labels, val_labels, test_labels

"""
Create image preprocessing and data augmentation pipelines for training and validation.

This function defines:
- Training transforms: includes data augmentation (flip, rotation, color jitter)
  to improve model generalization.
- Validation transforms: only resizing and normalization (no augmentation)
  to ensure fair and consistent evaluation.

Both pipelines normalize images using ImageNet mean and standard deviation,
making them compatible with pretrained models.
"""

def get_transforms(img_size=224):

    train_transform = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(20),
        transforms.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.2),
        transforms.RandomAffine(degrees=0, translate=(0.15, 0.15)),
        transforms.RandomGrayscale(p=0.1),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])
    

    val_transform = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    return train_transform, val_transform



"""
Custom PyTorch Dataset class for loading images and labels.

This class:
- Loads image paths and corresponding labels
- Applies optional transformations (augmentation / normalization)
- Returns image tensors and labels for model training

Args:
    images (list): List of image file paths
    labels (list): Corresponding class labels
    transform (callable, optional): Transformations to apply on images

Returns:
    tuple: (image tensor, label tensor)
"""

class MyDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        label = self.labels[idx]

        image = Image.open(img_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, torch.tensor(label)

"""
Create PyTorch DataLoaders for training, validation, and testing.

Args:
    train_dataset: Training dataset object
    val_dataset: Validation dataset object
    test_dataset: Test dataset object
    batch_size (int): Number of samples per batch
    num_workers (int): Number of subprocesses for data loading

Returns:
    tuple: (train_loader, val_loader, test_loader)
"""
def get_dataloaders(train_dataset, val_dataset, test_dataset,
                    batch_size=32, num_workers=0):

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers
    )

    return train_loader, val_loader, test_loader

def show_samples(dataset, n=8):
    """Display a grid of sample images with their class labels."""
    fig, axes = plt.subplots(1, n, figsize=(n * 2, 3))

    indices = np.random.choice(len(dataset), n, replace=False)

    for ax, idx in zip(axes, indices):
        image, label = dataset[idx]

        # Denormalize
        image = image.numpy().transpose(1, 2, 0)
        mean = np.array([0.485, 0.456, 0.406])
        std  = np.array([0.229, 0.224, 0.225])
        image = std * image + mean
        image = np.clip(image, 0, 1)

        ax.imshow(image)
        ax.set_title(IDX_TO_CLASS[label.item()], fontsize=9)
        ax.axis('off')

    plt.tight_layout()
    plt.show()

"""
    Compute evaluation metrics for classification model.

    Returns:
        dict: Contains accuracy, precision, recall, f1-score, and confusion matrix.
    """

def compute_metrics(y_true, y_pred):
    metrics = {
        "accuracy": accuracy_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred, average="weighted"),
        "precision": precision_score(y_true, y_pred,average="weighted"),
        "recall": recall_score(y_true, y_pred,average="weighted"),
        "confusion_matrix": confusion_matrix(y_true, y_pred)
    }
    return metrics

"""#Visualization"""

# Visualization of confusion_matrix
def plot_confusion_matrix(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.colorbar(im, ax=ax)
    ax.set(
        xticks=np.arange(len(CLASSES)),
        yticks=np.arange(len(CLASSES)),
        xticklabels=CLASSES,
        yticklabels=CLASSES,
        xlabel='Predicted',
        ylabel='True',
        title='Confusion Matrix'
    )
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, str(cm[i, j]),
                    ha='center', va='center',
                    color='white' if cm[i, j] > cm.max() / 2 else 'black')
    plt.tight_layout()
    plt.show()

#Visualization training_curves

def plot_training_curves(train_losses, val_losses, train_accs, val_accs):
    epochs = range(1, len(train_losses) + 1)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(epochs, train_losses, label='Train')
    ax1.plot(epochs, val_losses,   label='Val')
    ax1.set(title='Loss', xlabel='Epoch', ylabel='Loss')
    ax1.legend()

    ax2.plot(epochs, train_accs, label='Train')
    ax2.plot(epochs, val_accs,   label='Val')
    ax2.set(title='Accuracy', xlabel='Epoch', ylabel='Accuracy')
    ax2.legend()

    plt.tight_layout()
    plt.show()

"""
Save and load model checkpoints during training.

This helps in:
- Resuming training from last saved epoch
- Saving model and optimizer states
- Preventing loss of progress in case of interruptions

Functions:
    save_checkpoint:
        Saves model weights, optimizer state, and current epoch.

    load_checkpoint:
        Loads saved states into model (and optimizer if provided)
        Returns last saved epoch for resuming training.
"""

def save_checkpoint(model, optimizer, epoch, path):
    torch.save({
        'epoch':                epoch,
        'model_state_dict':     model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
    }, path)
    print(f"Checkpoint saved → {path}")


def load_checkpoint(path, model, optimizer=None):
    checkpoint = torch.load(path, map_location='cpu', weights_only=False)
    model.load_state_dict(checkpoint['model_state_dict'])
    if optimizer:
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    print(f"Checkpoint loaded ← {path} (epoch {checkpoint['epoch']})")
    return checkpoint['epoch']

